[versions]
plugin-gradle-build-tools = "7.3.1"
plugin-kotlin-gradle = "1.8.10"
plugin-hilt-android = "2.44.2"
plugin-google-services = "4.4.0"
plugin-jacoco = "0.8.7"
plugin-detekt = "1.21.0"

androidx-core-ktx = "1.12.0"
androidx-lifecycle-runtime-ktx = "2.6.2"
androidx-appcompat = "1.7.0-alpha03"
coroutines = "1.7.3"
serialization = "1.5.0"
okhttp = "4.10.0"
retrofit-serialization-converter = "1.0.0"
emoji2 = "1.4.0"
jetpack-compose-version = "1.6.0-alpha06"
jetpack-compose-compiler-version = "1.4.3"
jetpack-compose-material3 = "1.2.0-alpha08"
jetpack-compose-theme-adapter = "1.2.1"
androidx-activity-compose = "1.7.2"
androidx-lifecycle-viewmodel-compose = "2.6.2"
androidx-runtime-compose = "2.6.2"
androidx-navigation-compose = "2.7.3"
androidx-hilt-navigation-compose = "1.0.0"
androidx-paging-compose = "3.2.1"
compose-accompanist = "0.27.0"
detekt-formatting = "1.20.0"
detekt-rules-compose = "1.0.0"
hilt-version = "2.44.2"
hilt-compiler = "1.0.0"
ksp = "1.8.20-1.0.11"
jdk-desugaring = "1.1.5"
coil = "2.4.0"
paging = "3.2.1"
datastore = "1.0.0"
room = "2.5.2"
compose-emoji-picker = "1.0.0-alpha10"
work-manager = "2.8.1"
firebase = "32.3.1"
about-libraries = "10.8.3"
oss-licenses = "10.8.3"
junit = "4.13.2"
test-core-ktx = "1.5.0"
test-ext = "1.1.5"
test-truth = "1.5.0"
test-runner = "1.5.2"
test-rules = "1.5.0"
mockito-kotlin = "4.0.0"
kotlinx-coroutines-test = "1.7.3"
core-testing = "2.2.0"
turbine = "1.0.0"
hilt-android-testing = "2.44.2"
hilt-android-compiler = "2.44.2"

#plugins
plugin-kotlin-android = "1.8.10"
plugin-kotlin-jvm = "1.7.20"
plugin-serialization = "1.7.20"
plugin-kover = "0.6.1"
agp = "7.3.1"
google-services = "4.3.15"
firebase-crashlytics = "2.9.9"
espresso-core = "3.5.1"
material = "1.9.0"


[libraries]
plugin-gradle-build-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "plugin-gradle-build-tools" }
plugin-kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "plugin-kotlin-gradle" }
plugin-hilt-android = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "plugin-hilt-android" }
plugin-google-services = { group = "com.google.gms", name = "google-services", version.ref = "plugin-google-services" }
plugin-jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "plugin-jacoco" }
plugin-detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "plugin-detekt" }

androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
okhttp = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization-converter" }
emoji2 = { group = "androidx.emoji2", name = "emoji2", version.ref = "emoji2" }

#compose
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "jetpack-compose-version" }
androidx-compose-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "jetpack-compose-version" }
androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "jetpack-compose-version" }
androidx-compose-preiew = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "jetpack-compose-version" }
androidx-compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "jetpack-compose-version" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "jetpack-compose-material3" }
jetpack-compose-theme-adapter = { group = "com.google.android.material", name = "compose-theme-adapter", version.ref = "jetpack-compose-theme-adapter" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }
androidx-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-runtime-compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging-compose" }

#accompanist
compose-accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "compose-accompanist" }
compose-accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "compose-accompanist" }

#detekt
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt-formatting" }
detekt-rules-compose = { group = "ru.kode", name = "detekt-rules-compose", version.ref = "detekt-rules-compose" }

#hilt
hilt-version = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-version" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
jdk-desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "jdk-desugaring" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
paging = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

#compose emoji picker
compose-emoji-picker = { group = "com.github.Abhimanyu14", name = "compose-emoji-picker", version.ref = "compose-emoji-picker" }

#work manager
work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-manager" }

#firebase
firebase = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }

#about libraries
about-libraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "about-libraries" }
about-libraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "about-libraries" }

#tesing
junit = { group = "junit", name = "junit", version.ref = "junit" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext" }
test-truth = { group = "androidx.test.ext", name = "truth", version.ref = "test-truth" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "core-testing" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt-android-testing" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android-compiler" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "jetpack-compose-version" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "jetpack-compose-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin-android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin-kotlin-jvm" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-serialization" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "plugin-kover" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "plugin-detekt" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "oss-licenses" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

gradle-build-tools = { id = "com.android.tools.build.gradle", version.ref = "plugin-gradle-build-tools" }
kotlin-gradle = { id = "org.jetbrains.kotlin.gradle.plugin", version.ref = "plugin-kotlin-gradle" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "plugin-hilt-android" }
jacoco = { id = "org.jacoco.core", version.ref = "plugin-jacoco" }
