name: financemanager
description: A simple finance manager app

# To prevent the private packages from being published to pub.dev using `flutter pub publish`.
publish_to: 'none'

# Version and build number for your application.
# A version number is three numbers separated by dots followed by an optional build number
# separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# `flutter pub outdated` - To see which dependencies have newer versions available
#
# `flutter pub upgrade --major-versions` - To automatically upgrade your package dependencies
# to the latest versions
dependencies:
  flutter:
    sdk: flutter

  # Adds Cupertino Icons font - Use with the CupertinoIcons class
  cupertino_icons: ^1.0.4

  intl: ^0.17.0
  provider: ^6.0.1

  # For finding commonly used locations on the device filesystem
  path_provider: ^2.0.8

  synchronized: ^3.0.0

  # sql
  sqflite: ^2.0.1
  sqlbrite: ^2.2.0

  # sqlite ORM
  moor_flutter: ^4.0.0

  # code generation
  built_value: ^8.1.3
  built_collection: ^5.1.1
  built_value_generator: ^8.1.3
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

dependency_overrides:
  moor: '4.4.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.17.10
  collection: ^1.15.0
  moor_generator: ^4.6.0+1
  freezed: ^1.1.0
  build_runner: ^2.1.7

  # The "flutter_lints" package contains a set of recommended lints.
  # The lint set is activated in `analysis_options.yaml`
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To include Material Icons font with your application
  uses-material-design: true

  # To add assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application
  # Each entry in this list should have a "family" key with the font family name,
  # and a "fonts" key with a list giving the asset and other descriptors for the font.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
